Added dependencies check

diff --git a/src/pointcloud-procedures/src/pointcloud-procedures-main b/src/pointcloud-procedures/src/pointcloud-procedures-main
--- a/src/pointcloud-procedures/src/pointcloud-procedures-main
+++ b/src/pointcloud-procedures/src/pointcloud-procedures-main
@@ -117,6 +117,57 @@ arguments() {
 
 }
 
+# Environement check status variable
+ENV_NOT_OK=""
+
+# Check OpenMVG
+if ! which openMVG_main_computeMatches >/dev/null; then
+
+    # Debug output
+    echo -e "[$(date '+%F %R') \e[31mERROR\e[39m] $(basename $0) : OpenMVG not installed"
+
+    # Flag error
+    ENV_NOT_OK="1"
+
+fi
+
+# Check cmvs
+if ! which cmvs >/dev/null; then
+
+    # Debug output
+    echo -e "[$(date '+%F %R') \e[31mERROR\e[39m] $(basename $0) : cmvs not installed"
+
+    # Flag error
+    ENV_NOT_OK="1"
+
+fi
+
+# Check pmvs 2
+if ! which pmvs2 >/dev/null; then
+
+    # Debug output
+    echo -e "[$(date '+%F %R') \e[31mERROR\e[39m] $(basename $0) : pmvs2 not installed"
+
+    # Flag error
+    ENV_NOT_OK="1"
+
+fi
+
+# Check GnoProj
+if ! which gnoproj >/dev/null; then
+
+    # Debug output
+    echo -e "[$(date '+%F %R') \e[31mERROR\e[39m] $(basename $0) : gnoproj not installed"
+
+    # Flag error
+    ENV_NOT_OK="1"
+
+fi
+
+# If a software is missing, exit
+if [ ! -z "$ENV_NOT_OK" ]; then exit; fi
+
+# Check arguments
 if [ $# -eq 0 ]; then
     _help
     exit
